/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package M2ijpahibernate;


import java.util.Iterator;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

import org.hibernate.cfg.Configuration;
import org.hibernate.service.ServiceRegistry;
import M2ijpahibernate.Entity.Actor;
import M2ijpahibernate.Entity.Country;
import M2ijpahibernate.Entity.Film;
import M2ijpahibernate.Entity.Language;


public class App {


    public static void main(String[] args) {
        searchInDB();
    }

    public static void searchInDB() {
        Session session;

        Configuration configuration = new Configuration().configure();
    
        // IMPORTANT : On ajoute bien nos Entités !!
        // configuration.addAnnotatedClass(Film.class);
        // configuration.addAnnotatedClass(Language.class);

        // IMPORTANT
        // ServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder().applySettings(configuration.getProperties()).build();

        SessionFactory sessionFactory = configuration.buildSessionFactory();
        session = sessionFactory.openSession();
        Language l = session.getReference(Language.class, 1);
        Iterator<Film> i = l.getFilmsParLangue().iterator();  
        while(i.hasNext()){
            System.out.println(i.next().getTitle());
        }

        session.close();
    }
}
